- name: Cache SonarCloud packages
  uses: actions/cache@v2
  with:
    path: ~/.sonar/cache
    key: ${{ runner.os }}-sonar

- name: SonarCloud Scan
  uses: SonarSource/sonarcloud-github-action@master
  with:
    projectBaseDir: .
  env:
    SONAR_TOKEN: ${{ secrets.xLuniel_ESTETICA-APP }}
